image: ghcr.io/eshattow/homeassistant-base
build_from: "alpine"
cosign:
  identity: https://github.com/eshattow/docker-base/.*
args:
  BASHIO_VERSION: 0.17.5
  TEMPIO_VERSION: 2024.11.2
  S6_OVERLAY_VERSION: 3.1.6.2
  JEMALLOC_VERSION: 5.3.0
labels:
  io.hass.base.name: alpine
  org.opencontainers.image.source: https://github.com/eshattow/docker-base
