image: ghcr.io/eshattow/homeassistant-base-ubuntu
build_from: "ubuntu"
cosign:
  identity: https://github.com/eshattow/docker-base/.*
args:
  BASHIO_VERSION: 0.17.5
  TEMPIO_VERSION: 2024.11.2
  S6_OVERLAY_VERSION: 3.1.6.2
labels:
  io.hass.base.name: ubuntu
  org.opencontainers.image.source: https://github.com/eshattow/docker-base
