image: ghcr.io/eshattow/homeassistant-base-python
build_from: "ghcr.io/eshattow/homeassistant-base"
cosign:
  base_identity: https://github.com/eshattow/docker-base/.*
  identity: https://github.com/eshattow/docker-base/.*
args:
  PYTHON_VERSION: "3.13.9"
  PIP_VERSION: "25.3"
  CERT_IDENTITY: thomas@python.org
  CERT_OIDC_ISSUER: https://accounts.google.com
labels:
  io.hass.base.name: python
  org.opencontainers.image.source: https://github.com/eshattow/docker-base
